// src/lib/atmosphere.ts
// Central atmosphere engine: maps genre/mood → CSS tokens + particle type
import type { AtmosphereConfig, MoodType } from '@/types'

export const ATMOSPHERE_PRESETS: Record<MoodType, AtmosphereConfig> = {
  horror: {
    mood:         'horror',
    bgColor:      '#0a0505',
    surfaceColor: '#140a0a',
    accentColor:  '#8b0000',
    textColor:    '#d4c4c4',
    mutedColor:   '#6b4f4f',
    borderColor:  '#2d1515',
    glowColor:    'rgba(139,0,0,0.6)',
    fontDisplay:  '"Crimson Text", Georgia, serif',
    fontBody:     '"EB Garamond", Georgia, serif',
    particles:    'fog',
    overlayClass: 'bg-gradient-to-b from-red-950/20 to-transparent',
  },
  romance: {
    mood:         'romance',
    bgColor:      '#1a0d10',
    surfaceColor: '#250f15',
    accentColor:  '#c97d8a',
    textColor:    '#f0dce0',
    mutedColor:   '#8c6068',
    borderColor:  '#3d2028',
    glowColor:    'rgba(201,125,138,0.5)',
    fontDisplay:  '"Playfair Display", Georgia, serif',
    fontBody:     '"Lora", Georgia, serif',
    particles:    'petals',
    overlayClass: 'bg-gradient-to-b from-rose-900/20 to-transparent',
  },
  fantasy: {
    mood:         'fantasy',
    bgColor:      '#050d1a',
    surfaceColor: '#0a1628',
    accentColor:  '#7b5ea7',
    textColor:    '#e8e0f0',
    mutedColor:   '#6a5a80',
    borderColor:  '#1e2a40',
    glowColor:    'rgba(123,94,167,0.6)',
    fontDisplay:  '"Cinzel", Georgia, serif',
    fontBody:     '"Raleway", sans-serif',
    particles:    'sparkles',
    overlayClass: 'bg-gradient-to-b from-purple-900/20 to-transparent',
  },
  thriller: {
    mood:         'thriller',
    bgColor:      '#080808',
    surfaceColor: '#101010',
    accentColor:  '#4a9eff',
    textColor:    '#cccccc',
    mutedColor:   '#555555',
    borderColor:  '#1e1e1e',
    glowColor:    'rgba(74,158,255,0.4)',
    fontDisplay:  '"Oswald", sans-serif',
    fontBody:     '"Source Sans 3", sans-serif',
    particles:    'rain',
    overlayClass: 'bg-gradient-to-b from-blue-950/10 to-transparent',
  },
  war: {
    mood:         'war',
    bgColor:      '#0c0a06',
    surfaceColor: '#16130b',
    accentColor:  '#b8860b',
    textColor:    '#d4cdb8',
    mutedColor:   '#6b6040',
    borderColor:  '#2a2416',
    glowColor:    'rgba(184,134,11,0.5)',
    fontDisplay:  '"Bebas Neue", sans-serif',
    fontBody:     '"Roboto Condensed", sans-serif',
    particles:    'embers',
    overlayClass: 'bg-gradient-to-b from-yellow-950/20 to-transparent',
  },
  adventure: {
    mood:         'adventure',
    bgColor:      '#070f0a',
    surfaceColor: '#0f1a12',
    accentColor:  '#2e8b57',
    textColor:    '#d0e8d8',
    mutedColor:   '#4a7058',
    borderColor:  '#1a2e20',
    glowColor:    'rgba(46,139,87,0.5)',
    fontDisplay:  '"Merriweather", serif',
    fontBody:     '"Open Sans", sans-serif',
    particles:    'none',
    overlayClass: 'bg-gradient-to-b from-green-950/20 to-transparent',
  },
  drama: {
    mood:         'drama',
    bgColor:      '#0e0c10',
    surfaceColor: '#181520',
    accentColor:  '#9b6b9b',
    textColor:    '#e0d8e8',
    mutedColor:   '#6a5a70',
    borderColor:  '#2a2030',
    glowColor:    'rgba(155,107,155,0.4)',
    fontDisplay:  '"Cormorant Garamond", serif',
    fontBody:     '"Libre Baskerville", serif',
    particles:    'none',
    overlayClass: 'bg-gradient-to-b from-purple-950/10 to-transparent',
  },
  mystery: {
    mood:         'mystery',
    bgColor:      '#060810',
    surfaceColor: '#0d1018',
    accentColor:  '#5b7fa6',
    textColor:    '#c8d0d8',
    mutedColor:   '#505a66',
    borderColor:  '#181e28',
    glowColor:    'rgba(91,127,166,0.5)',
    fontDisplay:  '"Spectral", serif',
    fontBody:     '"IBM Plex Serif", serif',
    particles:    'fog',
    overlayClass: 'bg-gradient-to-b from-slate-900/30 to-transparent',
  },
  default: {
    mood:         'default',
    bgColor:      '#0f0f0f',
    surfaceColor: '#1a1a1a',
    accentColor:  '#e0c97f',
    textColor:    '#e8e0d0',
    mutedColor:   '#6b6555',
    borderColor:  '#2a2820',
    glowColor:    'rgba(224,201,127,0.4)',
    fontDisplay:  '"Playfair Display", serif',
    fontBody:     '"Lora", serif',
    particles:    'none',
    overlayClass: '',
  },
}

export function getAtmosphere(mood: MoodType): AtmosphereConfig {
  return ATMOSPHERE_PRESETS[mood] ?? ATMOSPHERE_PRESETS.default
}

// Convert AtmosphereConfig to CSS custom properties object
export function atmosphereToCSSVars(cfg: AtmosphereConfig): Record<string, string> {
  return {
    '--atmo-bg':      cfg.bgColor,
    '--atmo-surface': cfg.surfaceColor,
    '--atmo-accent':  cfg.accentColor,
    '--atmo-text':    cfg.textColor,
    '--atmo-muted':   cfg.mutedColor,
    '--atmo-border':  cfg.borderColor,
    '--atmo-glow':    cfg.glowColor,
    '--font-display': cfg.fontDisplay,
    '--font-body':    cfg.fontBody,
  }
}
